name: CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  VITE_SERVER_URL: ${{ vars.SERVER_URL }}

jobs:
  web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build -- --base /blingpot/

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/web/dist/"
      - id: deployment
        uses: actions/deploy-pages@v4
