name: CI

on:
  push:

env:
  VITE_SERVER_URL: ${{ vars.SERVER_URL }}

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run lint
      - run: npm run build

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - run: go vet ./...
      - run: go test ./...
      - run: go build -v ./cmd/blingpot/main.go
